[character]
success_symbol = "[❯❯](bold green)"
error_symbol = "[❯❯](bold red)"
vimcmd_symbol = "[\\[N\\]❮](bold green)"
vimcmd_replace_one_symbol = "[\\[r\\]❮](bold purple)"
vimcmd_replace_symbol = "[\\[R\\]❮](bold purple)"
vimcmd_visual_symbol = "[\\[V\\]❮](bold yellow)"
